# Generated by Django 2.2.16 on 2022-06-19 07:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_post_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
