# Generated by Django 2.2.16 on 2022-06-25 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0011_auto_20220623_1023'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title',
            field=models.CharField(default='--Без заголовка--', help_text='Введите заголовок поста', max_length=500, verbose_name='Заголовок поста'),
            preserve_default=False,
        ),
    ]
